name: .NET Build & Test

on:
  push:
    branches: "*"
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Check Installed SDKs & Runtimes
      run: |
        dotnet --list-sdks
        dotnet --list-runtimes

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests
      run: dotnet test MultithreadDownload.UnitTests/MultithreadDownload.UnitTests.csproj --no-build --verbosity normal

    - name: Run Integration Tests
      run: dotnet test MultithreadDownload.IntegrationTests/MultithreadDownload.IntegrationTests.csproj --no-build --verbosity normal
