name: .NET Build & Test

on:
  push:
    branches: [ "main", "feature/v3.1.0-docs-and-tests" ]
  pull_request:
    branches: [ "main", "feature/v3.1.0-docs-and-tests" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET (6.0 + 8.0)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests
      run: dotnet test MultithreadDownload.UnitTests/MultithreadDownload.UnitTests.csproj --no-build --verbosity normal

    - name: Run Integration Tests
      run: dotnet test MultithreadDownload.IntegrationTests/MultithreadDownload.IntegrationTests.csproj --no-build --verbosity normal
